### ISSUE TITLE
Location of Non-data columns parameter

### ISSUE THREAD

**Issue by ionurchin** [smith-chem-wisc/MetaNetwork#43]
Hello.  In the MetaNetwork Wiki the workflow step , Data file format,  indicates that there exists somewhere a setting one can change to indicate how many non-data columns there are.  This seems to default to 1 but I would like to have for example Gene names and Protein names in the data file following the Accession column.  Where can I set this value to e.g. 3? It doesn't appear in the web browser GUI. 

I'm running Linux Mint v20.3 and have used the latest Docker to run MetaNetwork.  Browser is FireFox, latest version.

Best regards,
Brian

**Comment by trishorts** [comment]
thanks Brian. we'll get back to you shortly.

**Comment by avcarr2** [comment]
Hi, sorry for the delay. That is an outdated instruction that I've now removed from the wiki. Non-value columns are now automatically identified.
